package com.gempukku.lotro.common;

public enum Keyword {
    ELF, HOBBIT, DWARF, MAN,
    URUK_HAI, NAZGUL, ORC,

    SUPPORT_AREA, SKIRMISH, FELLOWSHIP, RESPONSE, MANEUVER, ARCHERY,

    RING_BOUND, RING_BEARER,

    ROAMING,

    WEATHER, TALE,

    RIVER, PLAINS, UNDERGROUND,

    DAMAGE, DEFENDER, FIERCE, ARCHER, RANGER,

    HAND_WEAPON, ARMOR, HELM, MOUNT, RANGED_WEAPON, CLOAK
}
