var hobbit = {
    '30_1': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Ancestral_Knowledge.png',
    '30_2': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Balin.png',
    '30_3': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Battle_fury.png',
    '30_4': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Battle_of_Azanulbizar.png',
    '30_5': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bifur.png',
    '30_6': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bofur.png',
    '30_7': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bombur.png',
    '30_8': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dori.png',
    '30_9': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dwalin.png',
    '30_10': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Fili.png',
    '30_11': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gloin.png',
    '30_12': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Kili.png',
    '30_13': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Lore_of_Imladris.png',
    '30_14': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Noble_intentions.png',
    '30_15': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Nori.png',
    '30_16': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Oin.png',
    '30_17': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orcrist.png',
    '30_18': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Ori.png',
    '30_19': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thorin.png',
    '30_20': 'http://hobbitdraftgame.free.fr/Cards_Good_def/To_me_o_my_kinsfolk.png',
    '30_21': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Elrond.png',
    '30_22': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bard.png',
    '30_23': 'http://hobbitdraftgame.free.fr/Cards_Good_def/A_wizard_is_never_late.png',
    '30_24': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dawn_take_you_all.png',
    '30_25': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gandalf.png',
    '30_26': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gandalf2.png',
    '30_27': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gandalf3.png',
    '30_28': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gandalf4.png',
    '30_29': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Glamdring.png',
    '30_30': 'http://hobbitdraftgame.free.fr/Cards_Good_def/He_gives_me_courage.png',
    '30_31': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Take_up_arms.png',
    '30_32': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Anger.png',
    '30_33': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Fimbul.png',
    '30_34': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Hatred_Rekindled.png',
    '30_35': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Host_of_Thousands.png',
    '30_36': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Narzug.png',
    '30_37': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Not_At_Home.png',
    '30_38': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orkish_Marauder.png',
    '30_39': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orkish_Sneak.png',
    '30_40': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Watchful_Orc.png',
    '30_41': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Yazneg.png',
    '30_42': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Footman.png',
    '30_43': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bilbo.png',
    '30_44': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bilbo_Collector_of_Treasures.png',
    '30_45': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bilbo_Master_in_Riddles.png',
    '30_46': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bilbo_Reliable_Companion.png',
    '30_47': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Sting.png',
    '30_48': 'http://hobbitdraftgame.free.fr/Cards_Good_def/The_one_ring.png',
    '30_49': 'http://hobbitdraftgame.free.fr/Cards_Good_def/1_Bag_End.png',
    '30_50': 'http://hobbitdraftgame.free.fr/Cards_Good_def/2_The_Troll_Hoard.png',
    '30_51': 'http://hobbitdraftgame.free.fr/Cards_Good_def/3_Rivendell.png',
    '30_52': 'http://hobbitdraftgame.free.fr/Cards_Good_def/4_Goblin_Town.png',
    '30_53': 'http://hobbitdraftgame.free.fr/Cards_Good_def/5_Mirkwood.png',
    '30_54': 'http://hobbitdraftgame.free.fr/Cards_Good_def/6_Esgaroth.png',
    '30_55': 'http://hobbitdraftgame.free.fr/Cards_Good_def/7_Erebor.png',
    '30_56': "http://hobbitdraftgame.free.fr/Cards_Good_def/8_Smaug's_den.png",
    '30_57': 'http://hobbitdraftgame.free.fr/Cards_Good_def/9_Battle_of_the_five_armies.png',
    '30_58': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Smaug.png'
    '31_1': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dwarven_Axe.png'
    '31_2': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dwarven_Song.png'
    '31_3': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Emeralds_of_Girion.png'
    '31_4': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Great_Barricade.png'
    '31_5': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Mithril_Coat.png'
    '31_6': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Oakenshield.png'
    '31_7': 'http://hobbitdraftgame.free.fr/Cards_Good_def/The_Arkenstone.png'
    '31_8': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Elf_Army.png'
    '31_9': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Legolas.png'
    '31_10': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Tauriel.png'
    '31_11': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Evil_Becomes_Stronger.png'
    '31_12': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thranduil.png'
    '31_13': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Beorn.png'
    '31_14': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Eagles_Are_Coming.png'
    '31_15': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gwaihir.png'
    '31_16': 'http://hobbitdraftgame.free.fr/Cards_Good_def/His_Wrath_Was_Redoubled.png'
    '31_17': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Radagast.png'
    '31_18': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wizard_Staff.png'
    '31_19': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gollum_Better_Than_Nothing.png'
    '31_20': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gollum_Gollum.png'
    '31_21': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gollum_If_He_Loses.png'
    '31_22': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Riddles_in_the_Dark.png'
    '31_23': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wargs_Azog.png'
    '31_24': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wargs_Bolg.png'
    '31_25': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Savage_Warg.png'
    '31_26': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wargs_Threatening_Warg.png'
    '31_27': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wargs_Warg.png'
    '31_28': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wargs_War-Warg.png'
    '31_29': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Ancestral_Feuds.png'
    '31_30': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Goblin_Runner.png'
    '31_31': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Goblin_Scimitar.png'
    '31_32': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Goblin_Sneak.png'
    '31_33': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Song.png'
    '31_34': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Goblin_Swarms.png'
    '31_35': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Great_Goblin_s_power.png'
    '31_36': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_The_Great_Goblin.png'
    '31_37': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bolg_Servant.png'
    '31_38': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Acorn.png'
    '31_39': 'http://hobbitdraftgame.free.fr/Cards_Good_def/An_Invisible_Ring.png'
    '31_40': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Barrels.png'
    '31_41': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Burglar_s_Contract.png'
    '31_42': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Old_Thrush.png'
    '31_43': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Skillful_Negociator.png'
    '31_44': 'http://hobbitdraftgame.free.fr/Cards_Good_def/1_Bilbo_s_kitchen.png'
    '31_45': 'http://hobbitdraftgame.free.fr/Cards_Good_def/2_Trollshaw_Forest.png'
    '31_46': 'http://hobbitdraftgame.free.fr/Cards_Good_def/3_Rhudaur.png'
    '31_47': 'http://hobbitdraftgame.free.fr/Cards_Good_def/4_Beorn_House.png'
    '31_48': 'http://hobbitdraftgame.free.fr/Cards_Good_def/4_Underground_Lake.png'
    '31_49': 'http://hobbitdraftgame.free.fr/Cards_Good_def/4_Wooded_Steep_Cliff.png'
    '31_50': 'http://hobbitdraftgame.free.fr/Cards_Good_def/5_Forest_River.png'
    '31_51': 'http://hobbitdraftgame.free.fr/Cards_Good_def/5_Old_Forest_Road.png'
    '31_52': 'http://hobbitdraftgame.free.fr/Cards_Good_def/6_Lake_Town.png'
    '31_53': 'http://hobbitdraftgame.free.fr/Cards_Good_def/7_Dale.png'
    '31_54': 'http://hobbitdraftgame.free.fr/Cards_Good_def/9_Ravenhill.png'
    '31_55': 'http://hobbitdraftgame.free.fr/Cards_Good_def/9_Thror_Throne.png'
    '31_56': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Shadow_Arkenstone.png'
    '31_57': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Crazy_Cob.png'
    '31_58': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Enchanted_River.png'
    '31_59': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Fat_Spider.png'
    '31_60': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Lazy_Lob.png'
    '31_61': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Old_Tomnoddy.png'
    '31_62': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Spider_Nest.png'
    '31_63': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Wicked_Spider.png'
    '31_64': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Troll_Bert.png'
    '31_65': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Caught_In_A_Sack.png'
    '31_66': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Troll_Tom.png'
    '31_67': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Troll_William.png'
    '31_68': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Troll_Troll_Knife.png'
    '31_69': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Troll_Troll_Campfire.png'
    '32_1': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Crown_of_Erebor.png'
    '32_2': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dain.png'
    '32_3': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Du_Bekar.png'
    '32_4': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dwarven_Spear.png'
    '32_5': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Iron_Hills_Army.png'
    '32_6': 'http://hobbitdraftgame.free.fr/Cards_Good_def/King_Under_the_Mountain.png'
    '32_7': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Ring_of_Thror.png'
    '32_8': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Roac.png'
    '32_9': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thrain.png'
    '32_10': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thror_s_Heirlooms.png'
    '32_11': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thror_s_Key.png'
    '32_12': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thror_s_Map.png'
    '32_13': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Galadriel.png'
    '32_14': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Nenya.png'
    '32_15': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bain.png'
    '32_16': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Black_arrow.png'
    '32_17': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Esgaroth_Volunteers.png'
    '32_18': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Iron_Forged_Weapon.png'
    '32_19': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Percy.png'
    '32_20': 'http://hobbitdraftgame.free.fr/Cards_Good_def/The_Master.png'
    '32_21': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Former_Herald.png'
    '32_22': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gathering_of_the_three_rings.png'
    '32_23': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Narya.png'
    '32_24': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Saruman.png'
    '32_25': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bolg_Commander.png'
    '32_26': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Hidden_Attack.png'
    '32_27': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orkish_Bow.png'
    '32_28': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orkish_Pursuer.png'
    '32_29': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orkish_Veteran.png'
    '32_30': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orc_Army.png'
    '32_31': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Alfrid.png'
    '32_32': 'http://hobbitdraftgame.free.fr/Cards_Good_def/War_for_Gold.png'
    '32_33': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Assaulting_Goblin.png'
    '32_34': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Azog_Commander.png'
    '32_35': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Azog_s_Mace.png'
    '32_36': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Azog_Servant.png'
    '32_37': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dark_Bats.png'
    '32_38': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Demolition_Troll.png'
    '32_39': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wolves_Army.png'
    '32_40': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Vicious_Warg.png'
    '32_41': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Were_worms.png'
    '32_42': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Danger_Wrapped_in_Shadows.png'
    '32_43': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Jail.png'
    '32_44': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Shadow_Ring_of_Thror.png'
    '32_45': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Sauron.png'
    '32_46': 'http://hobbitdraftgame.free.fr/Cards_Good_def/1_Bilbo_s_kitchen.png'
    '32_47': 'http://hobbitdraftgame.free.fr/Cards_Good_def/2_Trollshaw_Forest.png'
    '32_48': 'http://hobbitdraftgame.free.fr/Cards_Good_def/3_Rhudaur.png'
    '32_49': 'http://hobbitdraftgame.free.fr/Cards_Good_def/4_Wooded_Steep_Cliff.png'
    '32_50': 'http://hobbitdraftgame.free.fr/Cards_Good_def/5_Dol_Guldur.png'
    '32_51': 'http://hobbitdraftgame.free.fr/Cards_Good_def/5_Old_Forest_Road.png'
    '32_52': 'http://hobbitdraftgame.free.fr/Cards_Good_def/6_Lake_Town.png'
    '32_53': 'http://hobbitdraftgame.free.fr/Cards_Good_def/6_Town_Hall.png'
    '32_54': 'http://hobbitdraftgame.free.fr/Cards_Good_def/7_Dale.png'
    '32_55': 'http://hobbitdraftgame.free.fr/Cards_Good_def/7_Secret_Door.png'
    '32_56': 'http://hobbitdraftgame.free.fr/Cards_Good_def/9_Northern_Slopes.png'
    '32_57': 'http://hobbitdraftgame.free.fr/Cards_Good_def/9_Ravenhill.png'
    '32_58': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dissension.png'
    '32_59': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dragon_Malice.png'
    '32_60': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Smaug_s_Awakening.png'
    '32_61': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Terrifying_Legend.png'
    '32_62': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Twisted_Gold_of_Dragon.png'
    '32_63': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wrath_of_the_Dragon.png'
    '32_64': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dol_Guldur_Blade.png'
    '32_65': 'http://hobbitdraftgame.free.fr/Cards_Good_def/He_is_summoning_his_servants.png'
    '32_66': 'http://hobbitdraftgame.free.fr/Cards_Good_def/The_Great_Enemy.png'
    '32_67': 'http://hobbitdraftgame.free.fr/Cards_Good_def/The_Witch_King.png'
    '32_68': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Attea.png'
    '32_69': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Cantea.png'
    '32_70': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Enquea.png'
    '32_71': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Lemenya.png'
    '32_72': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Nelya.png'
    '32_73': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Nertea.png'
    '32_74': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Otsea.png'
    '32_75': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Toldea.png'
}
