var hobbit = {
    '21_1': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Ancestral_Knowledge.png',
    '21_2': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Balin.png',
    '21_3': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Battle_fury.png',
    '21_4': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Battle_of_Azanulbizar.png',
    '21_5': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bifur.png',
    '21_6': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bofur.png',
    '21_7': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bombur.png',
    '21_8': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dori.png',
    '21_9': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dwalin.png',
    '21_10': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Fili.png',
    '21_11': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gloin.png',
    '21_12': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Kili.png',
    '21_13': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Lore_of_Imladris.png',
    '21_14': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Noble_intentions.png',
    '21_15': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Nori.png',
    '21_16': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Oin.png',
    '21_17': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orcrist.png',
    '21_18': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Ori.png',
    '21_19': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thorin.png',
    '21_20': 'http://hobbitdraftgame.free.fr/Cards_Good_def/To_me_o_my_kinsfolk.png',
    '21_21': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Elrond.png',
    '21_22': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bard.png',
    '21_23': 'http://hobbitdraftgame.free.fr/Cards_Good_def/A_wizard_is_never_late.png',
    '21_24': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dawn_take_you_all.png',
    '21_25': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gandalf.png',
    '21_26': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gandalf2.png',
    '21_27': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gandalf3.png',
    '21_28': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gandalf4.png',
    '21_29': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Glamdring.png',
    '21_30': 'http://hobbitdraftgame.free.fr/Cards_Good_def/He_gives_me_courage.png',
    '21_31': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Take_up_arms.png',
    '21_32': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Anger.png',
    '21_33': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Fimbul.png',
    '21_34': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Hatred_Rekindled.png',
    '21_35': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Host_of_Thousands.png',
    '21_36': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Narzug.png',
    '21_37': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Not_At_Home.png',
    '21_38': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orkish_Marauder.png',
    '21_39': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orkish_Sneak.png',
    '21_40': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Watchful_Orc.png',
    '21_41': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Yazneg.png',
    '21_42': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Footman.png',
    '21_43': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bilbo.png',
    '21_44': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bilbo_Collector_of_Treasures.png',
    '21_45': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bilbo_Master_in_Riddles.png',
    '21_46': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bilbo_Reliable_Companion.png',
    '21_47': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Sting.png',
    '21_48': 'http://hobbitdraftgame.free.fr/Cards_Good_def/The_one_ring.png',
    '21_49': 'http://hobbitdraftgame.free.fr/Cards_Good_def/1_Bag_End.png					',
    '21_50': 'http://hobbitdraftgame.free.fr/Cards_Good_def/2_The_Troll_Hoard.png',
    '21_51': 'http://hobbitdraftgame.free.fr/Cards_Good_def/3_Rivendell.png',
    '21_52': 'http://hobbitdraftgame.free.fr/Cards_Good_def/4_Goblin_Town.png',
    '21_53': 'http://hobbitdraftgame.free.fr/Cards_Good_def/5_Mirkwood.png',
    '21_54': 'http://hobbitdraftgame.free.fr/Cards_Good_def/6_Esgaroth.png',
    '21_55': 'http://hobbitdraftgame.free.fr/Cards_Good_def/7_Erebor.png',
    '21_56': "http://hobbitdraftgame.free.fr/Cards_Good_def/8_Smaug's_den.png",
    '21_57': 'http://hobbitdraftgame.free.fr/Cards_Good_def/9_Battle_of_the_five_armies.png',
    '21_58': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Smaug.png'
    '22_1': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dwarven_Axe.png'
    '22_2': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dwarven_Song.png'
    '22_3': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Emeralds_of_Girion.png'
    '22_4': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Great_Barricade.png'
    '22_5': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Mithril_Coat.png'
    '22_6': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Oakenshield.png'
    '22_7': 'http://hobbitdraftgame.free.fr/Cards_Good_def/The_Arkenstone.png'
    '22_8': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Elf_Army.png'
    '22_9': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Legolas.png'
    '22_10': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Tauriel.png'
    '22_11': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Evil_Becomes_Stronger.png'
    '22_12': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thranduil.png'
    '22_13': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Beorn.png'
    '22_14': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Eagles_Are_Coming.png'
    '22_15': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gwaihir.png'
    '22_16': 'http://hobbitdraftgame.free.fr/Cards_Good_def/His_Wrath_Was_Redoubled.png'
    '22_17': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Radagast.png'
    '22_18': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wizard_Staff.png'
    '22_19': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gollum_Better_Than_Nothing.png'
    '22_20': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gollum_Gollum.png'
    '22_21': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gollum_If_He_Loses.png'
    '22_22': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Riddles_in_the_Dark.png'
    '22_23': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wargs_Azog.png'
    '22_24': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wargs_Bolg.png'
    '22_25': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Savage_Warg.png'
    '22_26': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wargs_Threatening_Warg.png'
    '22_27': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wargs_Warg.png'
    '22_28': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wargs_War-Warg.png'
    '22_29': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Ancestral_Feuds.png'
    '22_30': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Goblin_Runner.png'
    '22_31': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Goblin_Scimitar.png'
    '22_32': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Goblin_Sneak.png'
    '22_33': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Song.png'
    '22_34': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Goblin_Swarms.png'
    '22_35': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_Great_Goblin_s_power.png'
    '22_36': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Goblin_The_Great_Goblin.png'
    '22_37': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bolg_Servant.png'
    '22_38': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Acorn.png'
    '22_39': 'http://hobbitdraftgame.free.fr/Cards_Good_def/An_Invisible_Ring.png'
    '22_40': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Barrels.png'
    '22_41': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Burglar_s_Contract.png'
    '22_42': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Old_Thrush.png'
    '22_43': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Skillful_Negociator.png'
    '22_44': 'http://hobbitdraftgame.free.fr/Cards_Good_def/1_Bilbo_s_kitchen.png'
    '22_45': 'http://hobbitdraftgame.free.fr/Cards_Good_def/2_Trollshaw_Forest.png'
    '22_46': 'http://hobbitdraftgame.free.fr/Cards_Good_def/3_Rhudaur.png'
    '22_47': 'http://hobbitdraftgame.free.fr/Cards_Good_def/4_Beorn_House.png'
    '22_48': 'http://hobbitdraftgame.free.fr/Cards_Good_def/4_Underground_Lake.png'
    '22_49': 'http://hobbitdraftgame.free.fr/Cards_Good_def/4_Wooded_Steep_Cliff.png'
    '22_50': 'http://hobbitdraftgame.free.fr/Cards_Good_def/5_Forest_River.png'
    '22_51': 'http://hobbitdraftgame.free.fr/Cards_Good_def/5_Old_Forest_Road.png'
    '22_52': 'http://hobbitdraftgame.free.fr/Cards_Good_def/6_Lake_Town.png'
    '22_53': 'http://hobbitdraftgame.free.fr/Cards_Good_def/7_Dale.png'
    '22_54': 'http://hobbitdraftgame.free.fr/Cards_Good_def/9_Ravenhill.png'
    '22_55': 'http://hobbitdraftgame.free.fr/Cards_Good_def/9_Thror_Throne.png'
    '22_56': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Shadow_Arkenstone.png'
    '22_57': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Crazy_Cob.png'
    '22_58': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Enchanted_River.png'
    '22_59': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Fat_Spider.png'
    '22_60': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Lazy_Lob.png'
    '22_61': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Old_Tomnoddy.png'
    '22_62': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Spider_Nest.png'
    '22_63': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Spider_Wicked_Spider.png'
    '22_64': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Troll_Bert.png'
    '22_65': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Caught_In_A_Sack.png'
    '22_66': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Troll_Tom.png'
    '22_67': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Troll_William.png'
    '22_68': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Troll_Troll_Knife.png'
    '22_69': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Troll_Troll_Campfire.png'
    '23_1': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Crown_of_Erebor.png'
    '23_2': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dain.png'
    '23_3': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Du_Bekar.png'
    '23_4': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dwarven_Spear.png'
    '23_5': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Iron_Hills_Army.png'
    '23_6': 'http://hobbitdraftgame.free.fr/Cards_Good_def/King_Under_the_Mountain.png'
    '23_7': 'http://hobbitdraftgame.free.fr/Cards_Good_def/King_Under_the_Mountain.png'
    '23_8': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Ring_of_Thror.png'
    '23_9': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Roac.png'
    '23_10': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thrain.png'
    '23_11': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thror_s_Heirlooms.png'
    '23_12': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thror_s_Keypng'
    '23_13': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Thror_s_Map.png'
    '23_14': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Galadriel.png'
    '23_15': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Nenya.png'
    '23_16': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bain.png'
    '23_17': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Black_arrow.png'
    '23_18': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Esgaroth_Volunteers.png'
    '23_19': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Iron_Forged_Weapon.png'
    '23_20': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Percy.png'
    '23_21': 'http://hobbitdraftgame.free.fr/Cards_Good_def/The_Master.png'
    '23_22': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Former_Herald.png'
    '23_23': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Gathering_of_the_three_rings.png'
    '23_24': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Narya.png'
    '23_25': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Saruman.png'
    '23_26': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Bolg_Commander.png'
    '23_27': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Hidden_Attack.png'
    '23_28': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orkish_Bow.png'
    '23_29': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orkish_Pursuer.png'
    '23_30': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orkish_Veteran.png'
    '23_31': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Orc_Army.png'
    '23_32': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Alfrid.png'
    '23_33': 'http://hobbitdraftgame.free.fr/Cards_Good_def/War_for_Gold.png'
    '23_34': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Assaulting_Goblin.png'
    '23_35': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Azog_Commander.png'
    '23_36': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Azog_s_Mace.png'
    '23_37': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Azog_Servant.png'
    '23_38': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dark_Bats.png'
    '23_39': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Demolition_Troll.png'
    '23_40': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wolves_Army.png'
    '23_41': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Vicious_Warg.png'
    '23_42': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Were_worms.png'
    '23_43': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Danger_Wrapped_in_Shadows.png'
    '23_44': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Jail.png'
    '23_45': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Shadow_Ring_of_Thror.png'
    '23_46': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Sauron.png'
    '23_47': 'http://hobbitdraftgame.free.fr/Cards_Good_def/1_Bilbo_s_kitchen.png'
    '23_48': 'http://hobbitdraftgame.free.fr/Cards_Good_def/2_Trollshaw_Forest.png'
    '23_49': 'http://hobbitdraftgame.free.fr/Cards_Good_def/3_Rhudaur.png'
    '23_50': 'http://hobbitdraftgame.free.fr/Cards_Good_def/4_Wooded_Steep_Cliff.png'
    '23_51': 'http://hobbitdraftgame.free.fr/Cards_Good_def/5_Dol_Guldur.png'
    '23_52': 'http://hobbitdraftgame.free.fr/Cards_Good_def/5_Old_Forest_Road.png'
    '23_53': 'http://hobbitdraftgame.free.fr/Cards_Good_def/6_Lake_Town.png'
    '23_54': 'http://hobbitdraftgame.free.fr/Cards_Good_def/6_Town_Hall.png'
    '23_55': 'http://hobbitdraftgame.free.fr/Cards_Good_def/7_Dale.png'
    '23_56': 'http://hobbitdraftgame.free.fr/Cards_Good_def/7_Secret_Door.png'
    '23_57': 'http://hobbitdraftgame.free.fr/Cards_Good_def/9_Northern_Slopes.png'
    '23_58': 'http://hobbitdraftgame.free.fr/Cards_Good_def/9_Ravenhill.png'
    '23_59': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dissension.png'
    '23_60': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dragon_Malice.png'
    '23_61': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Smaug_s_Awakening.png'
    '23_62': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Terrifying_Legend.png'
    '23_63': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Twisted_Gold_of_Dragon.png'
    '23_64': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Wrath_of_the_Dragon.png'
    '23_65': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Dol_Guldur_Blade.png'
    '23_66': 'http://hobbitdraftgame.free.fr/Cards_Good_def/He_is_summoning_his_servants.png'
    '23_67': 'http://hobbitdraftgame.free.fr/Cards_Good_def/The_Great_Enemy.png'
    '23_68': 'http://hobbitdraftgame.free.fr/Cards_Good_def/The_Witch_King.png'
    '23_69': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Attea.png'
    '23_70': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Cantea.png'
    '23_71': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Enquea.png'
    '23_72': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Lemenya.png'
    '23_73': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Nelya.png'
    '23_74': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Nertea.png'
    '23_75': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Otsea.png'
    '23_76': 'http://hobbitdraftgame.free.fr/Cards_Good_def/Toldea.png'
}
