package com.gempukku.lotro.common;

public enum CardType implements Filterable {
    ADVENTURE, ALLY, COMPANION, CONDITION, FOLLOWER, MINION, POSSESSION, THE_ONE_RING,
    ARTIFACT, EVENT, SITE,
    DILEMMA, DOORWAY, EQUIPMENT, FACILITY, INCIDENT, INTERRUPT, MISSION, OBJECTIVE, PERSONNEL, SHIP,
    TACTIC, TIME_LOCATION, TRIBBLE, TROUBLE;
}
