package com.gempukku.lotro.logic.modifiers;

public enum ModifierFlag {
    HAS_TO_MOVE_IF_POSSIBLE,
    RING_TEXT_INACTIVE,
    SARUMAN_FIRST_SENTENCE_INACTIVE,
    WIN_CHECK_AFTER_SHADOW_RECONCILE,
    CANT_PLAY_FROM_DISCARD_OR_DECK,
    RING_BEARER_CANT_TAKE_THREAT_WOUNDS,
    SKIRMISH_ORDER_BY_FIRST_SHADOW_PLAYER
}
